services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "9876:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    # command: sh -c "npm install && npx prisma migrate dev --name init"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "12345:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb"
    depends_on:
      - db
    tty: true

volumes:
  pgdata:

